
export const GET_REQUEST = 'GET_REQUEST';
export const GET_FAILURE = 'GET_FAILURE';

export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const TASK_CREATED = 'TASK_CREATED';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const CLEAR_MSG = 'CLEAR_MSG'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';